provider:
  default:
    language: 12.18

files:
  - app.js
  - package.json
  - ../.config/ecosystem.config.js

environment:
  NODE_ENV: production
  PORT: 3000
  PM2_HOME: /root/.pm2

bootstrap:
  - npm -g install pm2
