framework:
  website: javalin.io
  version: 3.9

build:
  - mvn compile assembly:single

binaries:
  - target/server-1.0.0-jar-with-dependencies.jar

command: >
  java -server 
  -XX:+UseNUMA -XX:+UseParallelGC 
  -cp target/benchmark-0.0.1-SNAPSHOT-jar-with-dependencies.jar benchmark.javalin.Bench profiles=production
